# Generated by Django 4.0.6 on 2022-07-11 15:55

from django.db import migrations, models
import django.db.models.deletion
import podcast.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='image')),
                ('author', models.CharField(blank=True, max_length=512, verbose_name='author')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('link', models.URLField(blank=True, default='', max_length=255, verbose_name='link')),
                ('subtitle', models.CharField(blank=True, default='', max_length=512, verbose_name='subtitle')),
                ('keywords', models.CharField(blank=True, default='', max_length=512, verbose_name='keywords')),
                ('copyright', models.CharField(blank=True, max_length=512, verbose_name='copyright')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='image')),
                ('author', models.CharField(blank=True, max_length=512, verbose_name='author')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('audio', models.FileField(upload_to=podcast.models.podcast_directory_path, verbose_name='audio')),
                ('published', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.podcast')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
