# Generated by Django 4.0.6 on 2022-07-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='public_image',
            field=models.URLField(blank=True, verbose_name='public image'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='public_image',
            field=models.URLField(blank=True, verbose_name='public image'),
        ),
    ]
