# Generated by Django 4.0.5 on 2022-07-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='name',
        ),
        migrations.AddField(
            model_name='podcast',
            name='author',
            field=models.CharField(blank=True, max_length=512, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, upload_to='podcast/images', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='link',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='title',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('audio', models.FileField(blank=True, upload_to='podcast/episodes/', verbose_name='audio')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('published', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.podcast')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
