# Generated by Django 4.0.5 on 2022-07-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_remove_podcast_name_podcast_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio',
            field=models.FileField(blank=True, upload_to='daf/static/episodes/', verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, upload_to='daf/static/images', verbose_name='image'),
        ),
    ]
