# Generated by Django 4.0.5 on 2022-07-02 19:33

from django.db import migrations, models
import podcast.models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_alter_episode_audio_alter_podcast_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio',
            field=models.FileField(blank=True, upload_to=podcast.models.podcast_directory_path, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='image'),
        ),
    ]
