# Generated by Django 4.0.6 on 2022-07-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_alter_episode_audio_alter_podcast_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
