# Generated by Django 4.0.6 on 2022-07-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_podcast_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='copyright',
            field=models.CharField(blank=True, max_length=512, verbose_name='copyright'),
        ),
    ]
