# Generated by Django 4.0.6 on 2022-07-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_podcast_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='author',
            field=models.CharField(blank=True, max_length=512, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='title'),
        ),
    ]
