# Generated by Django 4.0.6 on 2022-07-11 09:42

from django.db import migrations, models
import podcast.models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_episode_author_episode_image_alter_episode_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio',
            field=models.FileField(upload_to=podcast.models.podcast_directory_path, verbose_name='audio'),
        ),
    ]
